import { Header } from '@/modules/layouts/components/header';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../shared/assets/styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'laumy fashion',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-[--view-height] overflow-x-hidden bg-background h-full ">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
